default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: teleogram_development

test:
  <<: *default
  database: teleogram_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
