name: Automated tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: PostgreSQL

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install Ruby dependencies
      run: bundle install
    - name: Initialize database
      run: bundle exec rails db:setup
    - name: Run tests
      run: bundle exec rails test